package Parcial1.sleepingbarber;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class Ventana extends javax.swing.JFrame {

    public Ventana() {
        initComponents();
        setTextFieldChanged(nChairsTextBox);
        startButton.setEnabled(false);
        stopButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        progressCut = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        waitingList = new javax.swing.JList();
        waitingLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        stateBarber = new javax.swing.JLabel();
        inChairLabel = new javax.swing.JLabel();
        chairStatus = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        nChairsTextBox = new javax.swing.JTextField();
        nChairsLabel = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        waitingList.setModel(model);
        jScrollPane1.setViewportView(waitingList);

        waitingLabel.setText("Clientes en espera:");

        stateLabel.setText("Estado Barbero:");

        stateBarber.setText("...");

        inChairLabel.setText("En silla:");

        chairStatus.setText("...");

        org.jdesktop.layout.GroupLayout containerLayout = new org.jdesktop.layout.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, containerLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(containerLayout.createSequentialGroup()
                        .add(stateLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stateBarber))
                    .add(containerLayout.createSequentialGroup()
                        .add(inChairLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chairStatus))
                    .add(progressCut, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(waitingLabel))
                .add(122, 122, 122))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, containerLayout.createSequentialGroup()
                        .add(waitingLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, containerLayout.createSequentialGroup()
                        .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(stateLabel)
                            .add(stateBarber))
                        .add(18, 18, 18)
                        .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(inChairLabel)
                            .add(chairStatus))
                        .add(31, 31, 31)
                        .add(progressCut, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(61, 61, 61))
        );

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        nChairsLabel.setText("Number Chairs:");

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(container, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(nChairsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nChairsTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(startButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stopButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(startButton)
                    .add(nChairsTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nChairsLabel)
                    .add(stopButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(container, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        
        //numero de sillas
        try{
            Integer.parseInt(nChairsTextBox.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid number");
            return;
        }
        
        final int numeroSillas  = Integer.parseInt(nChairsTextBox.getText());
      
        //Monitor
        final Monitor m = new Monitor(numeroSillas, stateBarber, model, chairStatus, progressCut);
        
        //Barbero
        final Barbero barbero = new Barbero(m, stateBarber, chairStatus, progressCut);
        
        List<Cliente> clientes = new ArrayList<Cliente>();
        
        
        //se inicializan los hilso del monitor y del barbero.
        new Thread(barbero).start();
        new Thread(m).start();
        
        //habilitar los botones
        startButton.setEnabled(false);
        stopButton.setEnabled(true);
        
        //inicializar clientes
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    int numCliente=0;
                    Random r = new Random();
                    while(true){
                        Thread.sleep(r.nextInt(10000));
                        if(m.clientesEspera<numeroSillas){
                            Cliente nuevo = new Cliente(m, barbero, model, stateBarber, ++numCliente);
                            Thread t = new Thread(nuevo);
                            t.start();
                        }else{
                            System.out.println("Llego un cliente y se fue");
                        }
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start(); 
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_stopButtonActionPerformed

    private void setTextFieldChanged(JTextField txt){
        final JTextField t = txt;
        DocumentListener documentListener = new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent de) {
                changeEnabled(de);
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                changeEnabled(de);
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                changeEnabled(de);
            }
        };
        txt.getDocument().addDocumentListener(documentListener);
    }
    
    private void changeEnabled(DocumentEvent event){
        DocumentEvent.EventType type = event.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE)){
 
        }
        else if (type.equals(DocumentEvent.EventType.INSERT)){
            if(nChairsTextBox.getText().length()>0){
                startButton.setEnabled(true);
            }
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE)){
           if(nChairsTextBox.getText().length()==0){
                startButton.setEnabled(false);
            } 
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chairStatus;
    private javax.swing.JPanel container;
    private javax.swing.JLabel inChairLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nChairsLabel;
    private javax.swing.JTextField nChairsTextBox;
    private javax.swing.JProgressBar progressCut;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel stateBarber;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel waitingLabel;
    private javax.swing.JList waitingList;
    private DefaultListModel model = new DefaultListModel();
    // End of variables declaration//GEN-END:variables
}
